### PR TITLE
Add unfurl options to payload

### PR DESCRIPTION
**Pull request by lucidlogic**
Get unfurl links and unfurl media to work

### CODE REVIEW

**Comment by nwilging** [comment]
looks good! Could you add a couple test cases here: https://github.com/nwilging/laravel-slack-bot/blob/develop/tests/Unit/Services/SlackApiServiceTest.php#L357 to ensure the options array is built properly

**Comment by nwilging** [comment]
actually, this should already be possible: https://github.com/nwilging/laravel-slack-bot/blob/develop/src/Services/SlackApiService.php#L142

Try:
```
$options = [
   'unfurl' => [
      'links' => ...,
      'media' => ...,
   ],
];
```

**Comment by lucidlogic** [comment]
> actually, this should already be possible: https://github.com/nwilging/laravel-slack-bot/blob/develop/src/Services/SlackApiService.php#L142
> 
> Try:
> 
> ```
> $options = [
>    'unfurl' => [
>       'links' => ...,
>       'media' => ...,
>    ],
> ];
> ```

**Comment by lucidlogic** [comment]
> actually, this should already be possible: https://github.com/nwilging/laravel-slack-bot/blob/develop/src/Services/SlackApiService.php#L142
> 
> Try:
> 
> ```
> $options = [
>    'unfurl' => [
>       'links' => ...,
>       'media' => ...,
>    ],
> ];
> ```

yes, however the $options['unfurl'] don't get save to the $payload array that gets returned
https://github.com/nwilging/laravel-slack-bot/blob/develop/src/Services/SlackApiService.php#L160

**Pull request closed without merging**
